### PR TITLE
Overriding managed version

### PR DESCRIPTION
**Pull request by claudio-rosati**
See https://github.com/ControlSystemStudio/cs-studio/issues/2023

### CODE REVIEW

**Comment by willrogers** [comment]
Actually, I've realised that we could remove all of lines 332-359.  These are old or irrelevant avoiding warnings that no longer exist.

**Comment by claudio-rosati** [comment]
I've removed lines 332-359... I'm trying to see what happens...

**Comment by claudio-rosati** [comment]
I've also removed the bad requirement on java 1.7.

**Comment by claudio-rosati** [comment]
THe only warning remained in org.csstudio.product is:

Version '3.9.101.201408150207' of plug-in 'org.eclipse.draw2d' is not available.	feature.xml	/org.csstudio.product.configuration.feature	line 25	Plug-in Problem

@willrogers  Can I leave the dependency but remove the specific version number?

**Comment by willrogers** [comment]
Good question.

The specific version is there because of this problem: https://github.com/ControlSystemStudio/cs-studio/issues/1818.  You probably get an error when this specific version is not in your target platform.

I'm not sure what's best to do here.

**Comment by kasemir** [comment]
I'd prefer to use the 'current' version of draw2d, the one that goes with the Eclipse release that we use at the time (which is still 4.5. should update to 4.6..). Yes, that has the widget activation problem  ControlSystemStudio/cs-studio#1818, but we have a workaround for it.
Requiring an older version of draw2d that's getting more out of sync with the rest of our Eclipse release is likely to result in other issues.

**Comment by claudio-rosati** [comment]
So, so you parrove the removal of that specific version number?

**Comment by kasemir** [comment]
Yes, I would remove the specific version number. (or update it to the one that goes with Eclipse 4.5, then update it to the one that goes with 4.6 once we move to 4.6, but simply leaving the specific number off and having Eclipse 4.6 as a target would be my more practical preference).

But again that's based on my preference of using the draw2d that comes with the current Eclipse version and accepting the workaround that we have for the widget activation error. Using the older draw2d avoids the error and needs no workaround, so I understand why some might prefer that.

**Comment by willrogers** [comment]
If we don't want this version then we should be able to remove the requirement on the plugin altogether.

@berryma4 added it in 4fcc3419.

**Comment by claudio-rosati** [comment]
So, not being unanimous on draw2d we can leave it as is now.
@berryma4 Can then this pull request be merged?

**Pull request merged**
