### PR TITLE
Updated preference category name

### PR DESCRIPTION
**Pull request by claudio-rosati**
Changed the name of the General preference category from
introCustomizationPreference to Welcome Page.

### CODE REVIEW

**Comment by berryma4** [comment]
Shouldn't this be:
``` name="%introCustomizationPreference.name" ```
and it's filled in by property?
@shroffk @kasemir @willrogers

**Comment by kasemir** [comment]
Where do you define introCustomizationPreference.name?
In org.csstudio.product/plugin.properties?

**Comment by claudio-rosati** [comment]
No, in org.csstudio.product/plugin.xml.
org.csstudio.product/plugin.properties contains only the definition of "aboutText"

**Comment by claudio-rosati** [comment]
I've tried the @berryma4 solution and it works, so now it is in the plugin.properties file.
Have I to do another pull-request and closing this one?

**Comment by kasemir** [comment]
Ordinarily you can keep pushing commits to the branch, i.e. the ESSICS:master, and this pull request will then show the added commits. So no new pull request.

**Comment by claudio-rosati** [comment]
I've committed the changes.

**Comment by berryma4** [comment]
thank you!

**Pull request merged**
