### PR TITLE
Community Edition

### PR DESCRIPTION
**Pull request by claudio-rosati**
Updated ImageLabeler to ver. 2.0, and the xxx-release.sh scripts to
write “Community Edition” affiliation on the splash-screen.

### CODE REVIEW

**Comment by claudio-rosati** [comment]
The updates will generate a splash-screen like the following:

splash

The 2 xxx-release.sh scripts can be easily modified to generate site-specific version with the appropriate affiliation string.

**Comment by berryma4** [comment]
very nice!
Thank you!

**Comment by willrogers** [comment]
Is it time to put ESS and DLS on the list of contributors?

**Comment by shroffk** [comment]
yes...they should be (should have been for awhile now)

**Pull request merged**
